version: "3.7"

services:
  db:
    image: postgres:15.1
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: env("POSTGRES_USER")
      POSTGRES_PASSWORD: env("POSTGRES_PASSWORD")
      POSTGRES_DB: env("POSTGRES_DB")

  nickelapp:
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file: ./.env.local
    command: yarn dev
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/home/node/app

volumes:
  data: