version: "3.7"

services:
  db:
    image: postgres:15.1
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local


  db-test:
    image: postgres:15.1
    env_file: ./.env.test.local

  nickelapp:
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file: ./.env.local
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db-test
    volumes:
      - .:/home/node/app

volumes:
  data: